### ISSUE TITLE
Does this Kivy server work with docker?

### ISSUE THREAD

**Issue by vaibhavviswanathan** [kivy/kivy-server#1]
Does this work with docker?

If so, could we have some documentation on how to use it?

Thankss!

**Comment by KeyWeeUsr** [comment]
This kivy-server repository isn't a server where you can *run* Kivy. Kivy is a GUI. This repository contains stuff such as https://kivy.org website, kivy blog/planet, IRC bot and many other tools that are used on our server.

However, yes, it can be run with docker. Each of those folders have a `Dockerfile` and there's the main `docker-compose.yml` file. No documentation though.
