### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/.kivy'

### ISSUE THREAD

**Issue by EtricKombat** [kivy/kivy-server#18]
While trying to run a simple kivy program in docker container getting the listed error 

![image](https://user-images.githubusercontent.com/33585301/90812228-67158900-e343-11ea-8bf1-7ea6c434bed2.png)

Can you guys please help me resolve this? , listed below the simple kivy program i used and Dockerfile that i tried out

kivy_app.py: 

from kivy.app import App
from kivy.uix.label import Label
class FirstKivy(App):
    def build(self):
        return Label(text="My Name is Kakidi!")
FirstKivy().run()

________________________
Dockerfile:

FROM ubuntu:18.04

RUN apt-get update \
  && apt-get install -y python3-pip python3-dev \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip
RUN apt-get update -y
RUN apt-get install -qqy x11-apps -y
COPY . /app
WORKDIR /app
RUN pip3 install kivy
RUN pip3 install kivy-garden
ENTRYPOINT ["python"]
CMD ["kivy_app.py"]

docker build .
docker run -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --user="$(id --user):$(id --group)" 8d6dfsdf60fcd

__________________________________

**Comment by EtricKombat** [comment]
@matham  , can you please help me on this?

**Comment by tshirtman** [comment]
Bugreports are not for questions
This is the wrong project anyway
Don't ping core devs, or anyone, unless you are answering a question they asked you.
Use the appropriate support channels for questions.

**Comment by EtricKombat** [comment]
Thank you @tshirtman
